use_frameworks!

platform :ios, '8.0'
source 'https://github.com/SnapKit/Masonry.git'
source 'https://github.com/CocoaPods/Specs.git'

target 'CxyCarPlateNumberKeyBoard_Example' do
  pod 'CxyCarPlateNumberKeyBoard', :path => '../'

  target 'CxyCarPlateNumberKeyBoard_Tests' do
    inherit! :search_paths

    
  end
end
